version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@carford.com.br"
      PGADMIN_DEFAULT_PASSWORD: "carford"
    ports:
      - "5432:80"
    restart: always
    depends_on:
      - db
    networks:
      - postgres-network

  web:
    build:
      context: .
      dockerfile: ./docker/dev/python/Dockerfile
    command: gunicorn -w 4 carford.wsgi -b 0.0.0.0:8000 --reload
    volumes:
      - ./code:/code
      - static_files:/static_files
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=settings.dev
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    depends_on:
      - db
    networks:
      - postgres-network


volumes:
  static_files:

networks:
  postgres-network:
    driver: bridge
